@startuml
'https://plantuml.com/component-diagram

[Player]
[Enemy]
[EnemyGeneration]
[GameEngine]
[Map]
[Collision]
[Weapon]
[Shop]
[Common]

[Collision] -(0- [Common]
[Player] -(0- [Weapon]
[Common] -0)- [Player]
[Common] -0)- [Enemy]
[Common] -0)- [Map]
[GameEngine] -(0- [Shop]
[Common] -0)- [GameEngine]
[Enemy] -0)- [EnemyGeneration]
note bottom of [EnemyGeneration]: Which one eats which
note right of [Common]: Are the lolipop notaions pointing the right way? \n

@enduml