@startuml
'https://plantuml.com/component-diagram

[Player]
[Enemy]
[EnemyGeneration]
[GameEngine]
[Map]
[Collision]
[Weapon]
[Shop]
[Common]
[EnemySPI]


[Collision] ..> [GameEngine]
[Player] <.. [Weapon]
[Common] <.. [Enemy]
[Common] <.. [Player]
[GameEngine] <.. [Map]
[GameEngine] -(0- [Shop] : "ShopSPI"
[Common] <.. [GameEngine]
[Enemy] -0)- [EnemyGeneration] : "EnemySPI"
[EnemySPI] <.. [Enemy]
[GameEngine] <.. [Enemy]
[GameEngine] <.. [Player]
[EnemyGeneration] ..> [GameEngine] : ""
/'note bottom of [EnemyGeneration]: Which one eats which
note right of [Common]: Are the lolipop notaions pointing the right way? \n
'/
@enduml